Repository MisterPeModder/Bomberman-Global-Offensive, pull requests merged in 2022-05, with the labels that each got.

#21 Windows compilation and CI
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  CMakePresets.json
Labels: CI/CD, cross-platform

#23 Logger
  .gitignore
  src/CMakeLists.txt
  src/logger/CMakeLists.txt
  src/logger/Logger.cpp
  src/logger/Logger.hpp
  src/main.cpp
Labels: enhancement

#24 Add code style and documentation guidelines
  CONTRIBUTING.md
Labels: documentation

#25 Web platform compilation and build configuration tweaks
  .gitignore
  CMakeLists.txt
  CMakePresets.json
  README.md
  cmake/CompilerFlags.cmake
  cmake/DetectCompiler.cmake
  cmake/Findraylib.cmake
  src/CMakeLists.txt
  src/logger/Logger.cpp
  src/logger/Logger.hpp
  src/main.cpp
  tests/CMakeLists.txt
Labels: cross-platform

#30 Redirect raylib logger outputs in log_raylib.txt
  .gitignore
  src/logger/Logger.cpp
  src/logger/Logger.hpp
  src/main.cpp
Labels: raylib

#34 Add scoped Mode3D and Drawing classes in raylib::core::scopes namespace
  src/main.cpp
  src/raylib/core/CMakeLists.txt
  src/raylib/core/Camera3D.hpp
  src/raylib/core/scoped.hpp
Labels: raylib

#44 Use std::filesystem::path instead of std::string_view for path in the Logger
  src/logger/Logger.cpp
  src/logger/Logger.hpp
Labels: cross-platform

#45 Build the test suite inside GH Actions
  .github/workflows/ci.yml
  tests/localization/test_ressource_file.cpp
Labels: bug

#54 CI Web Build & Switch to Ubuntu (22.04) for linux builds
  .codecov.yml
  .github/workflows/build-tests.yml
  .github/workflows/ci.yml
  .github/workflows/lints.yml
  .github/workflows/mirroring.yml
  .gitignore
  CMakeLists.txt
  CMakePresets.json
  README.md
  cmake/CompilerFlags.cmake
  src/localization/Ressources.hpp
  tests/CMakeLists.txt
  tests/localization/CMakeLists.txt
  tests/tests_dummy.cpp
Labels: CI/CD, cross-platform

#49 Add a makePath utility function
  src/CMakeLists.txt
  src/util/CMakeLists.txt
  src/util/util.hpp
Labels: cross-platform

#52 Add dynamic bit set helper class
  src/ecs/join.hpp
  src/util/BitSet.cpp
  src/util/BitSet.hpp
  src/util/CMakeLists.txt
  tests/CMakeLists.txt
  tests/util/CMakeLists.txt
  tests/util/tests_BitSet.cpp
Labels: enhancement, ECS

#40 Feature/1 raylib encapsulation textures
  src/raylib/CMakeLists.txt
  src/raylib/shapes/CMakeLists.txt
  src/raylib/shapes/Circle.cpp
  src/raylib/shapes/Circle.hpp
  src/raylib/textures/CMakeLists.txt
  src/raylib/textures/Image.cpp
  src/raylib/textures/Image.hpp
  src/raylib/textures/Texture2D.cpp
  src/raylib/textures/Texture2D.hpp
Labels: documentation, raylib

#56 Entity-Compnent-System Framework
  cmake/CompilerFlags.cmake
  src/CMakeLists.txt
  src/ecs/CMakeLists.txt
  src/ecs/Component.hpp
  src/ecs/Entity.hpp
  src/ecs/Storage.hpp
  src/ecs/System.hpp
  src/ecs/World.hpp
  src/ecs/join.hpp
  src/ecs/join/CMakeLists.txt
  src/ecs/join/Join.hpp
  src/ecs/join/Joinable.hpp
  src/ecs/join/MaybeJoin.hpp
  src/ecs/resource/CMakeLists.txt
  src/ecs/resource/Entities.cpp
  src/ecs/resource/Entities.hpp
  src/ecs/resource/Resource.hpp
  src/ecs/resource/Timer.cpp
  src/ecs/resource/Timer.hpp
  src/ecs/storage/CMakeLists.txt
  src/ecs/storage/MapStorage.hpp
  src/ecs/storage/MarkerStorage.hpp
  src/ecs/storage/Storage.hpp
  src/ecs/system/CMakeLists.txt
  src/ecs/system/System.hpp
  src/ecs/system/SystemData.hpp
  src/ecs/world/CMakeLists.txt
  src/ecs/world/Instances.hpp
  src/ecs/world/World.cpp
  src/ecs/world/World.hpp
  src/util/BitSet.hpp
  tests/CMakeLists.txt
  tests/ecs/CMakeLists.txt
  tests/ecs/tests_Join.cpp
  tests/ecs/tests_ecs.cpp
  tests/ecs/world/CMakeLists.txt
  tests/ecs/world/tests_Entities.cpp
  tests/ecs/world/tests_World.cpp
  tests/util/tests_BitSet.cpp
Labels: ECS, ECS: Entity, ECS: System, ECS: Component, cross-platform

#29 Feature/1 raylib encapsulation
  cmake/CompilerFlags.cmake
  src/CMakeLists.txt
  src/dummy.cpp
  src/logger/Logger.hpp
  src/main.cpp
  src/raylib/CMakeLists.txt
  src/raylib/core/CMakeLists.txt
  src/raylib/core/Camera3D.cpp
  src/raylib/core/Camera3D.hpp
  src/raylib/core/Color.cpp
  src/raylib/core/Color.hpp
  src/raylib/core/Cursor.cpp
  src/raylib/core/Cursor.hpp
  src/raylib/core/Mouse.hpp
  src/raylib/core/Vector2.cpp
  src/raylib/core/Vector2.hpp
  src/raylib/core/Vector3.cpp
  src/raylib/core/Vector3.hpp
  src/raylib/core/Window.cpp
  src/raylib/core/Window.hpp
  src/raylib/core/scoped.hpp
  src/raylib/model/Animation.cpp
  src/raylib/model/Animation.hpp
  src/raylib/model/BoundingBox.cpp
  src/raylib/model/BoundingBox.hpp
  src/raylib/model/CMakeLists.txt
  src/raylib/model/Model.cpp
  src/raylib/model/Model.hpp
  src/raylib/shapes/AShape.hpp
  src/raylib/shapes/CMakeLists.txt
  src/raylib/shapes/Circle.cpp
  src/raylib/shapes/Circle.hpp
  src/raylib/shapes/Cone.cpp
  src/raylib/shapes/Cone.hpp
  src/raylib/shapes/Cube.cpp
  src/raylib/shapes/Cube.hpp
  src/raylib/shapes/Cylinder.hpp
  src/raylib/shapes/Pixel.cpp
  src/raylib/shapes/Pixel.hpp
  src/raylib/shapes/Rectangle.cpp
  src/raylib/shapes/Rectangle.hpp
  src/raylib/shapes/Sphere.cpp
  src/raylib/shapes/Sphere.hpp
  src/raylib/textures/CMakeLists.txt
  src/raylib/textures/Image.cpp
  src/raylib/textures/Image.hpp
  src/raylib/textures/Texture2D.cpp
  src/raylib/textures/Texture2D.hpp
Labels: documentation, raylib
